export const progresses = [
  { color: "green", width: "40%" },
  { color: "brown", width: "20%" },
  { color: "black", width: "15%" },
  { color: "gold", width: "10%" },
  { color: "linen", width: "15%" },
];

export const summaryLists = [
  { title: "Education", num: 45, percent: "45" },
  { title: "Marketing", num: 7, percent: "20" },
  { title: "Office Issues", num: 20, percent: "35" },
  { title: "Entertainments", num: 15, percent: "12" },
  { title: "Other", num: 50, percent: "50" },
];

export const requests = [
  {
    subject: "Netflix Suscription",
    type: "Entertainment",
    users: ["jennifer", "aminat"],
    status: "Pending",
    amount: "10,000",
    date: "July 06, 2020",
    time: "11:00am",
    color: "gold",
  },
  {
    subject: "Udemy",
    type: "Education",
    users: ["oluwa", "odudu", "adejo"],
    status: "Approved",
    amount: "10,000",
    date: "July 06, 2020",
    time: "11:00am",
    color: "teal",
  },
  {
    subject: "Mac-Book laptop",
    type: "Office Issue",
    users: ["burna boy"],
    status: "Denied",
    amount: "10,000",
    date: "July 06, 2020",
    time: "11:00am",
    color: "brown",
  },
  {
    subject: "Netflix",
    type: "Marketing",
    users: ["mary", "lizzy"],
    status: "Postponed",
    amount: "10,000",
    date: "July 06, 2020",
    time: "11:00am",
    color: "grey",
  },
  {
    subject: "Netflix",
    type: "Education",
    users: ["john", "adam", "grace"],
    status: "Closed",
    amount: "10,000",
    date: "July 06, 2020",
    time: "11:00am",
    color: "purple",
  },
];
export const claims = [
  {
    subject: "Bottle Waters",
    type: "Entertainment",
    users: ["claim1", "issue", "lekan"],
    status: "Pending",
    amount: "10,000",
    date: "July 06, 2020",
    time: "11:00am",
    color: "gold",
  },
  {
    subject: "Github School",
    type: "Education",
    users: ["japa", "doe"],
    status: "Approved",
    amount: "10,000",
    date: "July 06, 2020",
    time: "11:00am",
    color: "teal",
  },
  {
    subject: "Laptop Issues",
    type: "Office Issue",
    users: ["onu"],
    status: "Denied",
    amount: "10,000",
    date: "July 06, 2020",
    time: "11:00am",
    color: "brown",
  },
  {
    subject: "Netflix",
    type: "Marketing",
    users: ["possible", "toyin"],
    status: "Postponed",
    amount: "10,000",
    date: "July 06, 2020",
    time: "11:00am",
    color: "grey",
  },
  {
    subject: "Netflix",
    type: "Education",
    users: ["chima", "ugo"],
    status: "Closed",
    amount: "10,000",
    date: "July 06, 2020",
    time: "11:00am",
    color: "purple",
  },
];
