export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const VERIFY_PASSWORD = "VERIFY_PASSWORD";
export const PASSWORD_ERROR = "PASSWORD_ERROR";
